### ISSUE TITLE
Is it OK to use a SortedSet concurrently from multiple BEAM processes?

### ISSUE THREAD

**Issue by jorendorff** [discordapp/sorted_set_nif#5]
Hi! I did a bunch of work on Rustler a while back, so I was excited to read [your blog post](https://blog.discordapp.com/using-rust-to-scale-elixir-for-11-million-concurrent-users-c6f19fc029d3) and take a look at the code.

It looks exactly how we imagined Rustler would be used in practice. I'm very grateful that you made this an open source library so I could see it. :)

----

My question is about concurrency and `SortedSet`.

The NIFs all [use `try_lock` to acquire the mutex](https://github.com/discordapp/sorted_set_nif/blob/master/native/sorted_set_nif/src/lib.rs#L140). I think that means that a SortedSet will work fine as long as only a single Erlang process uses it. If multiple processes try to use it concurrently, there could be sporadic `:lock_fail` errors. Are you using it within a single process? Have you seen errors?

**Comment by ihumanable** [comment]
The library was designed to be safely used concurrently.  It is possible to see a `:lock_fail` in practice I've only ever seen it happen in a concurrency stress test.

**Comment by ihumanable** [comment]
I'm going to close this issue out, please feel free to open an issue if you run into any concurrency problems and I will be happy to assist you.

**Comment by jorendorff** [comment]
Thanks!
